POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpbG1hayIsImlkIjoiNjE2ZmZkOWM5MTgzMGZmZTYzODRmODYxIiwiaWF0IjoxNjM0Nzk2MzkwfQ.YbO82CMm1a8JGjZsJo03-prol-xEKe5CfloMcyJPzMU

{
  "title": "Testblog14",
  "author": "Author Catorce",
  "url": "https://someotherurl.com",
  "likes": 6
}
